[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[tool.maturin]
features = ["pyo3/extension-module"]

[project]
name = "factored-componentize-py"
version = "0.20.7"
description = "Tool to package Python applications as WebAssembly components"
readme = "README.md"
license = { file = "LICENSE" }
keywords = [ "webassembly", "wasm", "component" ]

[project.urls]
repository = "https://github.com/pie-project/componentize-py"

[project.scripts]
componentize-py = "componentize_py:script"
